### ISSUE TITLE
Describe how this project differs from browserpass

### ISSUE THREAD

**Issue by jcassee** [martinhoefling/gopassbridge#1]
This extension seems to do the same thing (and looks based on the same code?) as [browserpass](https://github.com/dannyvankooten/browserpass). I wondered, what are the differences?

**Comment by martinhoefling** [comment]
So first of all, from a user perspective: It does (almost) the same thing but using [gopass](https://github.com/justwatchcom/gopass) instead of [pass](https://www.passwordstore.org/) as password store.

The three main differences are:

1. written to interface with the [gopass](https://github.com/justwatchcom/gopass) password manager, not [pass](https://www.passwordstore.org/).
2. just a browser plugin, the native messaging host api is directly implemented into gopass
3. The gopassbridge code is fully reviewable also when installed as extension: No 3rd party libraries, plain ES5, no bundling involved

Concerning the code: It is not a fork of browserpass but its written with browserpass in mind. I really liked the simplicity of the plugin ui, that's why the html structure and css are very similar at the moment.

Does that answer your question?

**Comment by jcassee** [comment]
Yes, thanks Martin! So the host API is in gopass itself, that's pretty cool! Still requires some manual installation, the wrapper, right? Or do you think you will be able to remove that step?

**Comment by martinhoefling** [comment]
I am currently working on [setting up things automatically](https://github.com/martinhoefling/gopass/tree/jsonapi), based on a few questions. It's tested partially and should work on OSX and Linux.

**Comment by jcassee** [comment]
Great! Thanks for that.
