### ISSUE TITLE
"Attempt to postMessage on disconnected port"

### ISSUE THREAD

**Issue by tylershuster** [martinhoefling/gopassbridge#2]
I receive the above error after installing on FirefoxDeveloperEdition 57.0b11 on MacOS 10.13.1 Beta with goPass 1.0.0, using the version of this plugin available in the Firefox App Store.

Any pointers in the right direction would be appreciated.

**Comment by martinhoefling** [comment]
You need at least gopass > 1.4.0, since the json API is not implemented in versions before. However, I recommend the newest version 1.5.1 as the setup of the native messaging manifest and gopass wrapper has been simplified. With 1.5.1, you can follow https://github.com/justwatchcom/gopass/blob/master/docs/setup.md#filling-in-passwords-from-browser to set up your browser. Please provide more details of your setup if this does not work for you or if the documentation is unclear.

**Comment by martinhoefling** [comment]
Closed with #4

**Comment by rounakdatta** [comment]
If you're facing this issue on firefox inspite of having the correct gopass-jsonapi version, the root cause must be that Firefox's  user group is not having the correct executable permissions. Experiment with
`chmod 777 /Users/foobar/Library/Application\ Support/Mozilla/NativeMessagingHosts/com.justwatch.gopass.json`

**Comment by pawsen** [comment]
> If you're facing this issue on firefox inspite of having the correct gopass-jsonapi version, the root cause must be that Firefox's user group is not having the correct executable permissions. Experiment with
> `chmod 777 /Users/foobar/Library/Application\ Support/Mozilla/NativeMessagingHosts/com.justwatch.gopass.json`

If the permissions are wrong you probably ran `gopass-jsonapi configure` with `sudo`. Note that the above is not enough then; you should problaby also change the permission of the `NativeMessagingHosts`.

Instead install the wrapper for single user:
```
sudo rm -rf /Users/foobar/Library/Application\ Support/Mozilla/NativeMessagingHosts/
gopass-jsonapi configure --browser firefox --path /Users/foobar/.config/gopass
ls -la '/Users/foobar/Library/Application Support/Mozilla/NativeMessagingHosts'
total 4
drwx------ 3 foobar staff  96 Nov 19 11:55 .
drwx------ 4 foobar staff 128 Nov 19 11:55 ..
-rw------- 1 foobar staff 270 Nov 19 11:55 com.justwatch.gopass.json
```
