### ISSUE TITLE
bad username when entry is selected

### ISSUE THREAD

**Issue by dummys** [martinhoefling/gopassbridge#5]
Hi,

When selecting password from the bridge window, the username get filled with the acutal name of the entry.
for example if my password is in `Internet/amazon.com`, then the username get populated by `amazon.com`. Can you help me figuring that please ?
Thanks

**Comment by martinhoefling** [comment]
Sure, this definitely needs some documentation.

There are two ways the username is determined. Lets assume you have an entry `Internet/amazon.com`. 

First, attempt is to read out the username from the metadata "login", "username", "user" fields in this order. So if your yaml metadata contains `username: myusername`, it's derived from that.

This should work fine for most cases but lets assume that you have multiple accounts. `Internet/amazon.com/user@work` and `Internet/amazon.com/user@private`. In the latter case, if the user cannot be read out from the metadata, `user@work` or `user@private` is used as fallback. 

In your example - since there is no suffix after `amazon.com`, amazon.com itself is selected which is obvious nonsense.

The following steps should be done imo:
- Add documentation how username is read out from metadata
- If no username could be derived, display error and do not fallback to domain name itself.

**Comment by dummys** [comment]
Ok. At the end I recreated my pass file with the format Internet/amazon.com/myuser. It's working good now

**Comment by martinhoefling** [comment]
Documentation improved in https://github.com/justwatchcom/gopass/pull/444
